### ISSUE TITLE
Appendix: Timing

### ISSUE THREAD

**Issue by igouy** [attractivechaos/plb2#13]
Cool!

Please, the appendix table is titled "Timing", so follow through on that acknowledgement of what is obviously most important.

Order the rows by "Timing" — same as the charts "nqueens + matmul".

Order the cols by "Timing" — same as the charts "nqueens + matmul" followed by the label, followed by the details.

**Comment by attractivechaos** [comment]
Thanks for the suggestion, but I will keep the table sorted mostly by label such that it is easier to find a language by eye.

**Comment by igouy** [comment]
I'm not trying to find a particular language, I'm trying to see how the timings vary.

An additional table with different ordering :-)

**Comment by attractivechaos** [comment]
You can now get the time-sorted table on the command line with:
```sh
analysis/parse-readme.pl README.md
```
