### ISSUE TITLE
Non nested matrices

### ISSUE THREAD

**Issue by henriksjostrom** [attractivechaos/plb2#33]
In https://github.com/attractivechaos/plb2#optimizing-inner-loops you describe using nested arrays.

Have you tried using a flat matrix while tracking the indices manually? In my experience that avoids an extra memory indirection and can lead to significant performance gains as the memory indirection is comparatively slow and performing an integer multiplication is faster than extra memory access.

Something like
```
for (int i = 0; i < n; ++i)
    for (int k = 0; k < n; ++k)
        for (int j = 0; j < n; ++j)
            c[i*n+j] += a[i*n+k] * b[k*n+j];
```

instead of
```
for (int i = 0; i < n; ++i)
    for (int k = 0; k < n; ++k)
        for (int j = 0; j < n; ++j)
            c[i][j] += a[i][k] * b[k][j];
```

**Comment by SpinTensor** [comment]
I just did a quick test with the C version of this BM on my laptop. The nested array version took on average 1.58s and the continuous array version 1.29s. As expected there is a benefit and it is close to my Fortran implementation of 1.21s (Fortran automatically deals with the mapping from nested to continuous array accesses.

**Comment by henriksjostrom** [comment]
almost a fifth less runtime is quite significant

**Comment by attractivechaos** [comment]
Not the case on my laptop. The C version already uses continuous memory. It can be turned into "i*n+j" with
```c
double *c0 = c[0], *a0 = a[0], *b0 = b[0];
for (i = 0; i < n; ++i)
  for (k = 0; k < p; ++k)
    for (j = 0; j < m; ++j)
      c0[i*m+j] += a0[i*p+k] * b0[k*m+j];
```
This version is a tiny bit slower:
```
Benchmark 1: ./matmul
  Time (mean ± σ):     540.9 ms ±   2.9 ms    [User: 531.4 ms, System: 7.9 ms]
  Range (min … max):   536.5 ms … 545.1 ms    10 runs

Benchmark 2: ./matmul-1d
  Time (mean ± σ):     557.0 ms ±   2.5 ms    [User: 547.0 ms, System: 8.1 ms]
  Range (min … max):   551.1 ms … 560.5 ms    10 runs

Summary
  ./matmul ran
    1.03 ± 0.01 times faster than ./matmul-1d
```
Mojo and Swift (and another implementation I forgot) are using "i*n+j". They are no faster. Fortran is indeed faster (see the timing is the updated table).

**Comment by adamsmasher** [comment]
FWIW I tried this in C# (which has built-in support for multidimensional arrays) and it was nearly twice as slow on my machine!

**Comment by henriksjostrom** [comment]
fair enough, guess it doesn't work here
