### ISSUE TITLE
V should be run with GC on

### ISSUE THREAD

**Issue by i582** [attractivechaos/plb2#35]
It’s quite strange to compare implementations when other languages clear allocated memory (spending time on this), but V does not:

```
==113615== Memcheck, a memory error detector
==113615== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==113615== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==113615== Command: ./nqueen
==113615== 
2279184
==113615== 
==113615== HEAP SUMMARY:
==113615==     in use at exit: 277 bytes in 6 blocks
==113615==   total heap usage: 7 allocs, 1 frees, 1,301 bytes allocated
==113615== 
==113615== LEAK SUMMARY:
==113615==    definitely lost: 277 bytes in 6 blocks
==113615==    indirectly lost: 0 bytes in 0 blocks
==113615==      possibly lost: 0 bytes in 0 blocks
==113615==    still reachable: 0 bytes in 0 blocks
==113615==         suppressed: 0 bytes in 0 blocks
==113615== Rerun with --leak-check=full to see details of leaked memory
==113615== 
==113615== For lists of detected and suppressed errors, rerun with: -s
==113615== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

Comparison GC-on with no-GC:

```
Benchmark 1: ./nqueen
  Time (mean ± σ):      2.213 s ±  0.010 s    [User: 2.209 s, System: 0.003 s]
  Range (min … max):    2.198 s …  2.229 s    10 runs

Benchmark 2: ./nqueen-gc
  Time (mean ± σ):      2.276 s ±  0.049 s    [User: 2.259 s, System: 0.016 s]
  Range (min … max):    2.228 s …  2.389 s    10 runs

Summary
  './nqueen' ran
    1.03 ± 0.02 times faster than './nqueen-gc'
```

Moreover, without GC, V has memory leaks even in simple programs [1], which makes comparing speed without GC even more strange.

[1] https://n-skvortsov-1997.github.io/reviews/#manual-memory-management

**Comment by ArtemkaKun** [comment]
Yes, I totally agree! I think Petr is right about V, it should be fixed 👍

After posting this text in the comments you will receive 100 rubles on your bank account. Don't forget to delete this part of the message.

**Comment by attractivechaos** [comment]
Ok, I think adding GC back is fair.

**Comment by attractivechaos** [comment]
Now V has GC enabled and also reads N from command-line arguments. Almost no changes in performance.

**Comment by i582** [comment]
ah, it looks like the commit that added this flag had no impact, so adding it back didn't change anything

**Comment by attractivechaos** [comment]
I know some people have complained about V, but I am quite impressed by it through this benchmark exercise. When I get time, I will port sudoku and bedcov to V and see how it feels to write V given more complex tasks.

**Comment by i582** [comment]
> I know some people have complained about V, but I am quite impressed by it through this benchmark exercise. When I get time, I will port sudoku and bedcov to V and see how it feels to write V given more complex tasks.

Yep, V is very cool, I really love it syntax
