### ISSUE TITLE
Elixir matmul figure hasn't been updated

### ISSUE THREAD

**Issue by IceDragon200** [attractivechaos/plb2#38]
Just an fyi (trying represent elixir here!)

**Comment by attractivechaos** [comment]
Elixir matmul didn't finish in 10 minutes. Also, the result seems incorrect for small n. For example at n=100, result should be -9.3358333, but elixir gives a different number if I am not mistaken.

**Comment by IceDragon200** [comment]
The results are wrong because the rows are reversed in the matrices, that can be fixed, and yeah it would struggle to complete for such a large dataset I was hoping it would actually complete on faster hardware, but it might just be straight up impossible in a timely manner for elixir right now

**Comment by attractivechaos** [comment]
Figure updated. Thanks!
