### ISSUE TITLE
License for the benchmarks and this repo

### ISSUE THREAD

**Issue by maximecb** [attractivechaos/plb2#40]
Hello. I saw your post on HN and wanted to maybe add your Ruby benchmark to YJIT's benchmark suite so that we can track and improve performance over time :)

However, I didn't see a license in this repo. Could you add an open source license to this repo in a `LICENSE` file? Would you be willing to use a CC-0 (Creative Commons Public Domain) license, just to make it as easy as possible for people to reuse the benchmarks?

**Comment by attractivechaos** [comment]
Just added CC0. With contributions from many developers, this is not my own work. Happy to make it public domain.
