### ISSUE TITLE
LLM usage

### ISSUE THREAD

**Issue by exclued** [attractivechaos/plb2#5]
Is it relevant to use LLM generation for missed exercises? At least for initial samples.

**Comment by attractivechaos** [comment]
I tried to let chatgpt4 translate sudoku from c/rust to nim/swift. The output has subtle but fatal logical errors in addition to many compiling errors. This becomes a bug hunting exercise in a language I am not familiar with. LLM seems not good enough to do the translation yet. Thanks you for the suggestion anyway.
