### ISSUE TITLE
C# AOT consideration

### ISSUE THREAD

**Issue by ZeBobo5** [attractivechaos/plb2#52]
Try to publish csharp apps as Native AOT.

Native AOT apps have faster startup time and smaller memory footprints.

**Comment by attractivechaos** [comment]
I thought it is AOT now. Any problems with the command line or the project file?

**Comment by leo-costa** [comment]
> I thought it is AOT now. Any problems with the command line or the project file?

It is AOT now.

**Comment by attractivechaos** [comment]
Thanks for the confirmation.
