### ISSUE TITLE
Error in README

### ISSUE THREAD

**Issue by SpinTensor** [attractivechaos/plb2#54]
There is an error in the README and it does not seem worthwhile to open a pull request for such a minor thing.
The matmul is not `axpy` but `gemm`. `axpy` is a vector on vector operation.

**Comment by attractivechaos** [comment]
gemm is for matrix multiplication. The inner loop is axpy: $y\gets ax+y$

**Comment by SpinTensor** [comment]
I did not see the `The inner loop resembles...` Sorry.
However, I think this is misleading and should be changed to: `The algorithm resembles a BLAS gemm...` (to be strict gemm with `beta  = 0`).
As it is currently it reads like it is n^2 (from the two outer loops) of axpy repetitions, which it formally ist, but not if you look at the execution performance. This is because in true axpy both vectors would be dense in memory and would allow for perfect cache usage. Here only one of the involved vectors lies densly in memory. The elements of the second one are accessed with a stride of n. Thus making it slower than n^2 axpy repetitions.

**Comment by attractivechaos** [comment]
I don't removed "axpy" to avoid confusion. Nonetheless, matrix multiplication is exact n^2 axpy and can be perfectly vectorized for large enough N. The implementation in D is more obvious:

https://github.com/attractivechaos/plb2/blob/6d8b75f0ad294ba6059ce68fad2bf4dbfcd40048/src/d/matmul.d#L17-L25

You can replace the inner loop with BLAS' axpy.
