### ISSUE TITLE
Consider using Accelerate for Swift matmul

### ISSUE THREAD

**Issue by wigging** [attractivechaos/plb2#56]
Apple provides the Accelerate framework for high performance matrix and vector operations in Swift. The Swift matmul benchmark in this repo would be much faster using Accelerate features. Can I submit such an example or would it not be suitable for this repository?

**Comment by attractivechaos** [comment]
The requirement is to implement the same algorithm in every language without language bindings or external libraries at the bottleneck. Using the Accelerate framework would violate this requirement. Thanks for your inference anyway.
