### ISSUE TITLE
Benchmark flaws elimination: code rules and compilation flags

### ISSUE THREAD

**Issue by cyrusmsk** [attractivechaos/plb2#58]
To make values more comparable, it will be good to identify some "rules" and forbidden/available things.
For language implementations:
* is it allowed to switch off bounds checking?
* usage of raw pointers?
* safe techniques?

Also it would be good to identify and synchronize compilation flags for AOT langs:
* use LTO?
* use PGO?
* use other flags for aggressive optimizations?

Because without similar settings - results could be very different.
Even with before mentioned rules - to have useful results it should be much more analysis, than just time for running, but without similar approach for both (code and compilation) phases - it is just the comparison of some random values...

**Comment by attractivechaos** [comment]
These are all allowed.

**Comment by cyrusmsk** [comment]
> These are all allowed.

Thank you.

I've also checking bedcov solutions for different langs and I'm not sure that the algorithms are the same for each languages.

Did the bench is checking the correctness in terms of similar operations and O(x)?

For example in index function for Rust
```rust
last_i = if last_i>>k&1 != 0 { last_i - x } else { last_i + x };
```
and for Crystal
```crystal
last_i = (last_i>>k&1) != 0 ? last_i - (1<<(k-1)) : last_i + (1<<(k-1))
```
the condition and signs "-"/"+" are same.
However for Julia they are different:
```julia
last_i = if ((last_i>>k&1) != 0) last_i + (1<<(k-1)) else last_i - (1<<(k-1)) end
```

Also for overlap function some languages using "yield" functionality, while others pushing results to a separate array.. I'm not sure it will work in the same way..

**Comment by attractivechaos** [comment]
The julia one is a typo; otherwise all three implementations use the same algorithm. Whether to use `x` or `1<<(k-1)` won't make a difference in performance. If it does, I am happy to accept a PR. Not all languages support `yield`. For those that support both `yield` and array append, you are free to use whichever is faster. Again, if the current implementation is not optimal, a PR will be appreciated.
