### ISSUE TITLE
Consider benchmarking using TruffleRuby Native

### ISSUE THREAD

**Issue by eregon** [attractivechaos/plb2#64]
Hello,

I did a run of the 3 Ruby benchmarks (with smaller input size) under:
* `ruby 3.3.0 (2023-12-25 revision 5124f9ac75) +YJIT [x86_64-linux]`
* `truffleruby 23.1.1, like ruby 3.2.2, Oracle GraalVM Native [x86_64-linux]` (`truffleruby-23.1.1-linux-amd64.tar.gz` from https://github.com/oracle/truffleruby/releases/tag/graal-23.1.1)

Here are my results on smaller input sizes (to keep it short), I used the average of 5 runs.

| benchmark and size | 3.3.0+YJIT | truffleruby |
| --- | --- | --- |
| src/ruby/matmul.rb 400 | 2165ms | 334ms |
| src/ruby/nqueen.rb 12 | 656ms | 199ms |
| src/ruby/sudoku.rb 5 | 811ms | 479ms |

So TruffleRuby is quite a bit faster (as expected as it's a more advanced JIT, [example results](https://eregon.me/blog/2022/01/06/benchmarking-cruby-mjit-yjit-jruby-truffleruby.html)).

Would it be possible to include TruffleRuby Native in your next run of benchmarking?
See https://github.com/oracle/truffleruby/blob/master/doc/user/installing-truffleruby.md for how to install.

**Comment by attractivechaos** [comment]
Thanks. I will consider. Which release from the download page to use?

**Comment by eregon** [comment]
Please use the latest release at the time at https://github.com/oracle/truffleruby/releases
(FYI, release schedule is https://www.graalvm.org/release-calendar/)

**Comment by attractivechaos** [comment]
Added. Thanks for the suggestion.

**Comment by attractivechaos** [comment]
I am very impressed by truffleruby.
