### ISSUE TITLE
Do you include the compilation time for AOT languages in the benchmark results?

### ISSUE THREAD

**Issue by maxfreu** [attractivechaos/plb2#8]
I'm asking this, because this would make things comparable to jitted languages. The other approach to make things more comparable would be to report timings from a second function invocation for the jitted languages, or some other benchmarking metric.

**Comment by jariji** [comment]
Fwiw the julia compilation time isn't all that bad, using `@time main()`:

```
sudoku 3.73%
matmul 2.40%
nqueen 0.69%
bedcov 0.88%
```

**Comment by maxfreu** [comment]
Haha, you probably looked at my profile and saw the julia packages :smile:  I think it's really up to what the benchmark maintainers want to compare: The runtime of functions or the entire program? Having a julia sysimage is maybe a bit overkill; probably no one would go so far to use it for simple projects. But I won't stop you :D

**Comment by igouy** [comment]
Some language implementations have runtime startup costs, which other language implementations avoid.

With the understanding that the tasks only need to be solved once, things already are comparable.
